title: Ian Waudby-Smith 
url: "https://ian.waudbysmith.com"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: no 
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Resume"
   link: "iws_resume.pdf"
 - name: "Contact"
   link: "contact"
